# Generated by Django 4.2.3 on 2023-07-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='DOB',
            new_name='Date_Of_Birth',
        ),
    ]
